[package]
name = "orderbook"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bcrypt = "0.17.1"
uuid = { version = "1.19.0", features = ["v4"] }

